birth_day = "29"
birth_month = "10"
birth_year = "2002"
expected_commitment = "0x01bf6afa4f50504c8542568c9d752381f25a7cc58490568498b503cc31288c71"
minimum_age = "18"
secret = "0x1f9c815bb3f29c20252feadab2cc9ca265c2c04205360f97b8721157732fe91a"
